### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Bumpr Branded Video App
email: n/a
description: Branded Video
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bumpr.video" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: 
github_username:    
author: Bumpr
logo: assets/images/large-logo.png
twitter:
  username: 
social:
  name: 
  links:
    - 

languages: ["en"]
ampdir: amp

# github: https://github.com/sandoche/Mobile-app-landingpage-template

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
  webmaster_verifications: google-site-verification=B4fqyLMgyIjyHHR57HMpwpaPR_z8hvLmzgus7WA1WzE
  google: B4fqyLMgyIjyHHR57HMpwpaPR_z8hvLmzgus7WA1WzE
  google_analytics: G-KGP9ERNE41

#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
