name: Bumpr
description: Be a lazy BUM and brand your video with BUMPR
full_description: 'More details coming soon...'
iOS: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png